<a href="https://colab.research.google.com/github/MaLuisa7/BusinessIntelligence_Class_master/blob/main/Pronostico_jerarquico_6X5_20231105.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Datos de https://app.powerbi.com/view?r=eyJrIjoiYTZhZThmZDEtMjgwMS00NDdjLWI0YjItNTM0MTU1M2ExZWJlIiwidCI6IjVlMmM0OTc3LTEwN2QtNDBhMy04YWY3LTcwMDc0ODFhNjBkNCIsImMiOjR9

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
sufi = ['_consumo', '_inv', '_vivienda']
top5 = ['BBVA México', 'Banamex','Banorte', 'Santander','Scotiabank']
sufi1 = ['consumo', 'vivienda', 'inv']

In [ ]:
from dateutil import relativedelta

# Function to convert the decimal representation to a datetime
def convert_decimal_to_datetime(decimal):
    year = int(decimal)
    month = int((decimal - year) * 12) + 1  # Adding 1 to make it a valid month (1-12)
    return f"{year}-{month:02d}-01"  # Format as "YYYY-MM-01"

In [ ]:
data_lst = []
for bank in top5:
  for su in sufi:
    path1 = '/content/'+bank+su+'.csv'
    dfn = pd.read_csv(path1)
    dfn['banco'] = bank
    dfn['tipoconsumo'] = su[1:]
    dfn['tipo'] = ['obs']*20 + ['fcast']*30
    # Apply the conversion function to the entire column
    dfn['date_column'] = dfn['Time'].apply(convert_decimal_to_datetime)

    # Convert the resulting strings to datetime objects
    dfn['date_column'] = pd.to_datetime(dfn['date_column'])

    data_lst.append(dfn)
    print(dfn.shape)
    display(dfn.head(1))

(50, 6)


Time         Value        banco tipoconsumo tipo date_column
0  2022.0  2.968921e+11  BBVA México     consumo  obs  2022-01-01

(50, 6)


Time         Value        banco tipoconsumo tipo date_column
0  2022.0  5.618641e+11  BBVA México         inv  obs  2022-01-01

(50, 6)


Time         Value        banco tipoconsumo tipo date_column
0  2022.0  2.666108e+11  BBVA México    vivienda  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  1.548223e+11  Banamex     consumo  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  5.605184e+11  Banamex         inv  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  6.817019e+10  Banamex    vivienda  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  1.209011e+11  Banorte     consumo  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  2.357007e+11  Banorte         inv  obs  2022-01-01

(50, 6)


Time         Value    banco tipoconsumo tipo date_column
0  2022.0  1.969357e+11  Banorte    vivienda  obs  2022-01-01

(50, 6)


Time         Value      banco tipoconsumo tipo date_column
0  2022.0  1.169544e+11  Santander     consumo  obs  2022-01-01

(50, 6)


Time         Value      banco tipoconsumo tipo date_column
0  2022.0  5.117842e+11  Santander         inv  obs  2022-01-01

(50, 6)


Time         Value      banco tipoconsumo tipo date_column
0  2022.0  1.786582e+11  Santander    vivienda  obs  2022-01-01

(50, 6)


Time         Value       banco tipoconsumo tipo date_column
0  2022.0  3.435035e+10  Scotiabank     consumo  obs  2022-01-01

(50, 6)


Time         Value       banco tipoconsumo tipo date_column
0  2022.0  1.254221e+11  Scotiabank         inv  obs  2022-01-01

(50, 6)


Time         Value       banco tipoconsumo tipo date_column
0  2022.0  1.634989e+11  Scotiabank    vivienda  obs  2022-01-01

In [ ]:
data = pd.concat(data_lst).reset_index(drop=True)
data.head()

Time         Value        banco tipoconsumo tipo date_column
0  2022.000000  2.968921e+11  BBVA México     consumo  obs  2022-01-01
1  2022.083333  2.978748e+11  BBVA México     consumo  obs  2022-01-01
2  2022.166667  3.027328e+11  BBVA México     consumo  obs  2022-03-01
3  2022.250000  3.076906e+11  BBVA México     consumo  obs  2022-04-01
4  2022.333333  3.133267e+11  BBVA México     consumo  obs  2022-04-01

In [ ]:
bbva_con = data.query("banco == @top5[0] & tipoconsumo == @sufi1[0]")
bbva_viv = data.query("banco == @top5[0] & tipoconsumo == @sufi1[1]")
bbva_inv = data.query("banco == @top5[0] & tipoconsumo == @sufi1[2]")
banamex_con = data.query("banco == @top5[1] & tipoconsumo == @sufi1[0]")
banamex_viv = data.query("banco == @top5[1] & tipoconsumo == @sufi1[1]")
banamex_inv = data.query("banco == @top5[1] & tipoconsumo == @sufi1[2]")
banorte_con = data.query("banco == @top5[2] & tipoconsumo == @sufi1[0]")
banorte_viv = data.query("banco == @top5[2] & tipoconsumo == @sufi1[1]")
banorte_inv = data.query("banco == @top5[2] & tipoconsumo == @sufi1[2]")
santander_con = data.query("banco == @top5[3] & tipoconsumo == @sufi1[0]")
santander_viv = data.query("banco == @top5[3] & tipoconsumo == @sufi1[1]")
santander_inv = data.query("banco == @top5[3] & tipoconsumo == @sufi1[2]")
scotia_con = data.query("banco == @top5[4] & tipoconsumo == @sufi1[0]")
scotia_viv = data.query("banco == @top5[4] & tipoconsumo == @sufi1[1]")
scotia_inv = data.query("banco == @top5[4] & tipoconsumo == @sufi1[2]")

In [ ]:
vivienda_nacional = pd.DataFrame()
vivienda_nacional['date_column'] = bbva_viv.date_column
vivienda_nacional['bbva'] = bbva_viv.Value.values
vivienda_nacional['banamex'] = banamex_viv.Value.values
vivienda_nacional['banorte'] = banorte_viv.Value.values
vivienda_nacional['santander'] = santander_viv.Value.values
vivienda_nacional['scotia'] = scotia_viv.Value.values
vivienda_nacional['nacional'] = vivienda_nacional.iloc[:,1:].sum(axis=1)
vivienda_nacional['tipo'] = bbva_viv.tipo.values
vivienda_nacional.reset_index(inplace=True, drop=True)

consumo_nacional = pd.DataFrame()
consumo_nacional['date_column'] = bbva_con.date_column.values
consumo_nacional['bbva'] = bbva_con.Value.values
consumo_nacional['banamex'] = banamex_con.Value.values
consumo_nacional['banorte'] = banorte_con.Value.values
consumo_nacional['santander'] = santander_con.Value.values
consumo_nacional['scotia'] = scotia_con.Value.values
consumo_nacional['nacional'] = consumo_nacional.iloc[:,1:].sum(axis=1)
consumo_nacional['tipo'] = bbva_con.tipo.values
consumo_nacional.reset_index(inplace=True, drop=True)


inversion_nacional = pd.DataFrame()
inversion_nacional['date_column'] = bbva_inv.date_column.values
inversion_nacional['bbva'] = bbva_inv.Value.values
inversion_nacional['banamex'] = banamex_inv.Value.values
inversion_nacional['banorte'] = banorte_inv.Value.values
inversion_nacional['santander'] = santander_inv.Value.values
inversion_nacional['scotia'] = scotia_inv.Value.values
inversion_nacional['nacional'] =inversion_nacional.iloc[:,1:].sum(axis=1)
inversion_nacional['tipo'] = bbva_inv.tipo.values
consumo_nacional.reset_index(inplace=True, drop=True)


display(vivienda_nacional.head())
display(consumo_nacional.head())
display(inversion_nacional.head())

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  2.666108e+11  6.817019e+10  1.969357e+11  1.786582e+11   
1  2022-01-01  2.681419e+11  6.730071e+10  1.974673e+11  1.798538e+11   
2  2022-03-01  2.711527e+11  6.711235e+10  1.991483e+11  1.815911e+11   
3  2022-04-01  2.735207e+11  6.622452e+10  2.001937e+11  1.833226e+11   
4  2022-04-01  2.762572e+11  6.560612e+10  2.018165e+11  1.854346e+11   

         scotia      nacional tipo  
0  1.634989e+11  8.738738e+11  obs  
1  1.649224e+11  8.776861e+11  obs  
2  1.675333e+11  8.865378e+11  obs  
3  1.693142e+11  8.925757e+11  obs  
4  1.716521e+11  9.007665e+11  obs

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  2.968921e+11  1.548223e+11  1.209011e+11  1.169544e+11   
1  2022-01-01  2.978748e+11  1.532222e+11  1.216949e+11  1.190207e+11   
2  2022-03-01  3.027328e+11  1.535165e+11  1.229163e+11  1.201733e+11   
3  2022-04-01  3.076906e+11  1.543331e+11  1.250258e+11  1.229061e+11   
4  2022-04-01  3.133267e+11  1.562795e+11  1.275217e+11  1.248182e+11   

         scotia      nacional tipo  
0  3.435035e+10  7.239202e+11  obs  
1  3.423938e+10  7.260521e+11  obs  
2  3.359970e+10  7.329386e+11  obs  
3  3.344268e+10  7.433984e+11  obs  
4  3.325079e+10  7.551969e+11  obs

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  5.618641e+11  5.605184e+11  2.357007e+11  5.117842e+11   
1  2022-01-01  5.516647e+11  5.379872e+11  2.317624e+11  4.958320e+11   
2  2022-03-01  5.433537e+11  5.670382e+11  2.373078e+11  4.969175e+11   
3  2022-04-01  5.188348e+11  5.818366e+11  2.388571e+11  4.772057e+11   
4  2022-04-01  5.390640e+11  5.721476e+11  2.473053e+11  4.808938e+11   

         scotia      nacional tipo  
0  1.254221e+11  1.995290e+12  obs  
1  1.194122e+11  1.936658e+12  obs  
2  1.129147e+11  1.957532e+12  obs  
3  1.300149e+11  1.946749e+12  obs  
4  1.308677e+11  1.970278e+12  obs

In [ ]:
s = np.matrix([[1,1,1,1,1],
              [1,0,0,0,0],
              [0,1,0,0,0],
              [0,0,1,0,0],
              [0,0,0,1,0],
              [0,0,0,0,1]])
print(s.shape)
print(s)

(6, 5)
[[1 1 1 1 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# y_tilde = S(S' S)^(-1) S' y_gorro
s1 =  s * np.linalg.inv(s.T * s) * s.T
print(s1.shape)
print(s1)

(6, 6)
[[ 0.83333333  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.83333333 -0.16666667 -0.16666667 -0.16666667 -0.16666667]
 [ 0.16666667 -0.16666667  0.83333333 -0.16666667 -0.16666667 -0.16666667]
 [ 0.16666667 -0.16666667 -0.16666667  0.83333333 -0.16666667 -0.16666667]
 [ 0.16666667 -0.16666667 -0.16666667 -0.16666667  0.83333333 -0.16666667]
 [ 0.16666667 -0.16666667 -0.16666667 -0.16666667 -0.16666667  0.83333333]]


In [ ]:
bancos = ['nacional', 'bbva',	'banamex',	'banorte',	'santander',	'scotia']
query1 = "tipo == 'fcast'"
query2 = "tipo == 'obs'"

In [ ]:

def pronostico_jerarquico(df_x):
  df_fcast = df_x.query(query1)
  df_fcast_values = df_fcast.loc[:, bancos]
  df_obs = df_x.query(query2)

  y_tilde = (s1*df_fcast_values.values.T).T
  df_jerarquico  = pd.DataFrame(y_tilde, columns = bancos)
  df_jerarquico['date_column'] = df_fcast.loc[:, ['date_column']].values
  df_jerarquico['tipo'] = df_fcast.loc[:, ['tipo']].values

  df_final = pd.concat([df_obs, df_jerarquico], axis =0).reset_index(drop=True)
  df_final.replace({'fcast': "fcast_jerarquico"}, inplace=True  )
  return df_final


In [ ]:
vivienda_jerarquico = pronostico_jerarquico(vivienda_nacional)
vivienda_jerarquico.head()

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  2.666108e+11  6.817019e+10  1.969357e+11  1.786582e+11   
1  2022-01-01  2.681419e+11  6.730071e+10  1.974673e+11  1.798538e+11   
2  2022-03-01  2.711527e+11  6.711235e+10  1.991483e+11  1.815911e+11   
3  2022-04-01  2.735207e+11  6.622452e+10  2.001937e+11  1.833226e+11   
4  2022-04-01  2.762572e+11  6.560612e+10  2.018165e+11  1.854346e+11   

         scotia      nacional tipo  
0  1.634989e+11  8.738738e+11  obs  
1  1.649224e+11  8.776861e+11  obs  
2  1.675333e+11  8.865378e+11  obs  
3  1.693142e+11  8.925757e+11  obs  
4  1.716521e+11  9.007665e+11  obs

In [ ]:
consumo_jerarquico = pronostico_jerarquico(consumo_nacional)
consumo_jerarquico.head()

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  2.968921e+11  1.548223e+11  1.209011e+11  1.169544e+11   
1  2022-01-01  2.978748e+11  1.532222e+11  1.216949e+11  1.190207e+11   
2  2022-03-01  3.027328e+11  1.535165e+11  1.229163e+11  1.201733e+11   
3  2022-04-01  3.076906e+11  1.543331e+11  1.250258e+11  1.229061e+11   
4  2022-04-01  3.133267e+11  1.562795e+11  1.275217e+11  1.248182e+11   

         scotia      nacional tipo  
0  3.435035e+10  7.239202e+11  obs  
1  3.423938e+10  7.260521e+11  obs  
2  3.359970e+10  7.329386e+11  obs  
3  3.344268e+10  7.433984e+11  obs  
4  3.325079e+10  7.551969e+11  obs

In [ ]:
inversion_jerarquico = pronostico_jerarquico(inversion_nacional )
inversion_jerarquico.head()

date_column          bbva       banamex       banorte     santander  \
0  2022-01-01  5.618641e+11  5.605184e+11  2.357007e+11  5.117842e+11   
1  2022-01-01  5.516647e+11  5.379872e+11  2.317624e+11  4.958320e+11   
2  2022-03-01  5.433537e+11  5.670382e+11  2.373078e+11  4.969175e+11   
3  2022-04-01  5.188348e+11  5.818366e+11  2.388571e+11  4.772057e+11   
4  2022-04-01  5.390640e+11  5.721476e+11  2.473053e+11  4.808938e+11   

         scotia      nacional tipo  
0  1.254221e+11  1.995290e+12  obs  
1  1.194122e+11  1.936658e+12  obs  
2  1.129147e+11  1.957532e+12  obs  
3  1.300149e+11  1.946749e+12  obs  
4  1.308677e+11  1.970278e+12  obs

In [ ]:
vivienda_nacional.to_csv("vivienda_nacional_20231105.csv")
vivienda_jerarquico.to_csv("vivienda_jerarquico_20231105.csv")
consumo_nacional.to_csv("consumo_nacional_20231105.csv")
consumo_jerarquico.to_csv("consumo_jerarquico_20231105.csv")
inversion_nacional.to_csv("inversion_nacional_20231105.csv")
inversion_jerarquico.to_csv("inversion_jerarquico_20231105.csv")

In [ ]:
vivienda_nacional.tail()

date_column          bbva       banamex       banorte     santander  \
45  2025-10-01  3.564842e+11  6.851160e+10  2.658284e+11  2.188433e+11   
46  2025-10-01  3.584194e+11  6.917841e+10  2.650288e+11  2.201185e+11   
47  2025-12-01  3.607344e+11  6.918270e+10  2.650265e+11  2.220467e+11   
48  2026-01-01  3.620173e+11  7.006078e+10  2.628102e+11  2.219125e+11   
49  2026-01-01  3.640574e+11  6.982627e+10  2.616550e+11  2.220990e+11   

          scotia      nacional   tipo  
45  2.673391e+11  1.177007e+12  fcast  
46  2.709802e+11  1.183725e+12  fcast  
47  2.752826e+11  1.192273e+12  fcast  
48  2.773586e+11  1.194159e+12  fcast  
49  2.797066e+11  1.197344e+12  fcast

In [ ]:
vivienda_nacional_fcast = vivienda_nacional.query('tipo == "fcast"')
vivienda_nacional_fcast

date_column          bbva       banamex       banorte     santander  \
20  2023-09-01  3.102457e+11  6.654848e+10  2.459216e+11  2.009579e+11   
21  2023-10-01  3.118695e+11  6.621163e+10  2.477714e+11  2.015064e+11   
22  2023-10-01  3.138066e+11  6.687844e+10  2.493445e+11  2.027902e+11   
23  2023-12-01  3.161231e+11  6.688273e+10  2.517148e+11  2.047248e+11   
24  2024-01-01  3.174069e+11  6.776081e+10  2.518711e+11  2.045954e+11   
25  2024-01-01  3.194477e+11  6.752630e+10  2.530885e+11  2.047857e+11   
26  2024-03-01  3.216055e+11  6.817528e+10  2.551347e+11  2.056343e+11   
27  2024-04-01  3.230807e+11  6.781517e+10  2.556496e+11  2.053563e+11   
28  2024-04-01  3.246011e+11  6.836522e+10  2.572817e+11  2.058227e+11   
29  2024-06-01  3.271906e+11  6.845746e+10  2.589415e+11  2.072120e+11   
30  2024-07-01  3.287257e+11  6.882577e+10  2.603008e+11  2.083077e+11   
31  2024-07-01  3.306902e+11  6.728271e+10  2.618374e+11  2.095025e+11   
32  2024-09-01  3.325591e+11  6.769847e+10  2.632542e+11  2.096535e+11   
33  2024-10-01  3.341800e+11  6.736161e+10  2.639177e+11  2.101912e+11   
34  2024-10-01  3.361152e+11  6.802842e+10  2.643045e+11  2.114667e+11   
35  2024-12-01  3.384303e+11  6.803271e+10  2.654885e+11  2.133951e+11   
36  2025-01-01  3.397132e+11  6.891079e+10  2.644584e+11  2.132611e+11   
37  2025-01-01  3.417533e+11  6.867629e+10  2.644895e+11  2.134477e+11   
38  2025-03-01  3.439106e+11  6.932526e+10  2.653495e+11  2.142937e+11   
39  2025-04-01  3.453856e+11  6.896516e+10  2.646780e+11  2.140136e+11   
40  2025-04-01  3.469057e+11  6.951521e+10  2.651239e+11  2.144785e+11   
41  2025-06-01  3.494951e+11  6.960744e+10  2.655974e+11  2.158666e+11   
42  2025-07-01  3.510300e+11  6.997576e+10  2.657703e+11  2.169613e+11   
43  2025-07-01  3.529945e+11  6.843269e+10  2.661207e+11  2.181555e+11   
44  2025-09-01  3.548633e+11  6.884845e+10  2.663511e+11  2.183059e+11   
45  2025-10-01  3.564842e+11  6.851160e+10  2.658284e+11  2.188433e+11   
46  2025-10-01  3.584194e+11  6.917841e+10  2.650288e+11  2.201185e+11   
47  2025-12-01  3.607344e+11  6.918270e+10  2.650265e+11  2.220467e+11   
48  2026-01-01  3.620173e+11  7.006078e+10  2.628102e+11  2.219125e+11   
49  2026-01-01  3.640574e+11  6.982627e+10  2.616550e+11  2.220990e+11   

          scotia      nacional   tipo  
20  2.023407e+11  1.026014e+12  fcast  
21  2.043517e+11  1.031711e+12  fcast  
22  2.070368e+11  1.039857e+12  fcast  
23  2.103831e+11  1.049828e+12  fcast  
24  2.115030e+11  1.053137e+12  fcast  
25  2.128949e+11  1.057743e+12  fcast  
26  2.151836e+11  1.065733e+12  fcast  
27  2.166411e+11  1.068543e+12  fcast  
28  2.191870e+11  1.075258e+12  fcast  
29  2.217557e+11  1.083557e+12  fcast  
30  2.244455e+11  1.090605e+12  fcast  
31  2.274598e+11  1.096773e+12  fcast  
32  2.304881e+11  1.103653e+12  fcast  
33  2.329771e+11  1.108628e+12  fcast  
34  2.361402e+11  1.116055e+12  fcast  
35  2.399646e+11  1.125311e+12  fcast  
36  2.415625e+11  1.127906e+12  fcast  
37  2.434325e+11  1.131799e+12  fcast  
38  2.461992e+11  1.139078e+12  fcast  
39  2.481347e+11  1.141177e+12  fcast  
40  2.511587e+11  1.147182e+12  fcast  
41  2.542054e+11  1.154772e+12  fcast  
42  2.573733e+11  1.161111e+12  fcast  
43  2.608657e+11  1.166569e+12  fcast  
44  2.643720e+11  1.172741e+12  fcast  
45  2.673391e+11  1.177007e+12  fcast  
46  2.709802e+11  1.183725e+12  fcast  
47  2.752826e+11  1.192273e+12  fcast  
48  2.773586e+11  1.194159e+12  fcast  
49  2.797066e+11  1.197344e+12  fcast

In [ ]:
bancos

['nacional', 'bbva', 'banamex', 'banorte', 'santander', 'scotia']

In [ ]:
vivienda_nacional_fcast.loc[:, ['bbva', 'banamex', 'banorte', 'santander', 'scotia']].sum()

bbva         1.011384e+13
banamex      2.050868e+12
banorte      7.814110e+12
santander    6.349706e+12
scotia       7.150724e+12
dtype: float64

In [ ]:
 vivienda_nacional_fcast.loc[:, ['nacional']].sum()

nacional    3.347925e+13
dtype: float64

In [ ]:
(vivienda_nacional_fcast.loc[:, ['bbva', 'banamex', 'banorte', 'santander', 'scotia']].sum() / vivienda_nacional_fcast.loc[:, ['nacional']].sum().values).sum()

0.9999999999999999

In [ ]:
(vivienda_jerarquico.loc[:, ['bbva', 'banamex', 'banorte', 'santander', 'scotia']].sum() / vivienda_jerarquico.loc[:, ['nacional']].sum().values).sum()

1.0